name: Deploy with Docker

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행됨

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t seuo/wannago-fe-image:latest .
          docker push seuo/wannago-fe-image:latest

  deploy:
    needs: build  # 🔥 'build' Job이 완료된 후에 실행되도록 강제
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.PEM_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PEM_KEY }}
          script: |
            docker pull seuo/wannago-fe-image:latest
            docker stop wannago_fe || true
            docker rm wannago_fe || true
            docker run -d --name wannago_fe -p 3000:3000 seuo/wannago-fe-image:latest
